import {Router} from "express";
import { protectRoute } from "../middleware/auth.middleware.js";
import {getAllUsers, getMessages, sendFriendRequest, acceptFriendRequest, rejectFriendRequest, removeFriend, updateProfile, getMutualFriends, getFriends, checkUsername, recordPlay, getTimeTravelStats, getRecommendedUsers, toggleLikeSong, getLikedSongs, uploadMedia} from "../controller/user.controller.js";
const router = Router();
router.post('/like/:songId', protectRoute, toggleLikeSong);
router.get('/liked-songs', protectRoute, getLikedSongs);
router.get('/recommendations', protectRoute, getRecommendedUsers);
router.get('/check-username', protectRoute, checkUsername);
router.post('/play-history', protectRoute, recordPlay);
router.get('/time-travel', protectRoute, getTimeTravelStats);
router.get('/',protectRoute,getAllUsers);
router.get('/messages/:userId',protectRoute,getMessages);
router.post('/messages/upload',protectRoute,uploadMedia);
router.post('/request/:userId',protectRoute,sendFriendRequest);
router.post('/accept/:userId',protectRoute,acceptFriendRequest);
router.post('/reject/:userId',protectRoute,rejectFriendRequest);
router.post('/remove/:userId',protectRoute,removeFriend);
router.put('/profile',protectRoute,updateProfile);
router.get('/profile/:userId/mutual',protectRoute,getMutualFriends);
router.get('/profile/:userId/friends',protectRoute,getFriends);
export default router